name: Go

on:
  push:
    branches: ["v2"]
  pull_request:
    branches: ["v2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -cover ./...
