name: golangci-lint

on:
  push:
    branches:
      - v2
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          args: --timeout=5m